.. Review the README on instructions to contribute.
.. Review the style guide to keep a consistent approach to the documentation.
.. Static objects, such as figures, should be stored in the _static directory. Review the _static/README on instructions to contribute.
.. Do not remove the comments that describe each section. They are included to provide guidance to contributors.
.. Do not remove other content provided in the templates, such as a section. Instead, comment out the content and include comments to explain the situation. For example:
	- If a section within the template is not needed, comment out the section title and label reference. Do not delete the expected section title, reference or related comments provided from the template.
    - If a file cannot include a title (surrounded by ampersands (#)), comment out the title from the template and include a comment explaining why this is implemented (in addition to applying the ``title`` directive).

.. This is the label that can be used for cross referencing this file.
.. Recommended title label format is "Directory Name"-"Title Name" -- Spaces should be replaced by hyphens.
.. _DP0-Delegate-Resources-Virtual-Events-Schedule:
.. Each section should include a label for cross referencing to a given area.
.. Recommended format for all labels is "Title Name"-"Section Name" -- Spaces should be replaced by hyphens.
.. To reference a label that isn't associated with an reST object such as a title or figure, you must include the link and explicit title using the syntax :ref:`link text <label-name>`.
.. A warning will alert you of identical labels during the linkcheck process.

.. This file does not contain a title because it is a table for another location (dp0-delegate-resources/index.rst).
.. title:: DP0 Delegate Assemblies Schedule
.. ################################
.. DP0 Delegate Assemblies Schedule
.. ################################

.. This section should provide a brief, top-level description of the page.

.. Use *italics* for tentative topics.

.. Use double-underscore for external links to prevent duplicate explicit target names.

.. list-table:: Rubin Science Assemblies schedule
   :header-rows: 1
   :widths: 1 1 3

   * - Date
     - Type
     - Topic
   * - 2024-03-07
     - tutorial
     - `(Re-)Introduction to DP0.2 and DP0.3 <https://community.lsst.org/t/rubin-science-assembly-thu-07-march-2024-re-introduction-to-dp0-2-and-dp0-3/8339/2>`_ (Jeff Carlin)
   * - 2024-03-14
     - drop-in
     - Q&A with Rubin staff, co-working time
   * - 2024-03-21
     - tutorial
     - `How to upload tables to the Portal Aspect <https://community.lsst.org/t/rubin-science-assembly-thu-21-march-2024-how-to-upload-tables-to-the-portal-aspect/8390/4>`_ (Christina Williams)
   * - 2024-03-28
     - drop-in
     - Q&A with Rubin staff, co-working time
   * - 2024-04-04
     - tutorial
     - `Phase curve analysis in the Portal Aspect <https://community.lsst.org/t/rubin-science-assembly-thu-4-april-2024-at-9-am-pdt-pd0-3-phase-curve-fit-analysis-in-the-portal-aspect/8429>`_ (Yumi Choi)
   * - 2024-04-11
     - drop-in
     - Q&A with Rubin staff, co-working time
   * - 2024-04-18
     - tutorial
     - `How to create custom coadds <https://community.lsst.org/t/rubin-science-assembly-thu-18-april-2024-at-9-am-pdt-how-to-create-custom-coadds/8473/2>`_ (Aaron Meisner)
   * - 2024-04-25
     - drop-in
     - Q&A with Rubin staff, co-working time
   * - 2024-05-02
     - tutorial
     - How to analyze the LSST point-spread function (PSF; Andrés Plazas Malagón)
   * - 2024-05-16
     - tutorial
     - How to use the image cutout service (Christina Williams)
   * - 2024-05-23
     - drop-in
     - Q&A with Rubin staff, co-working time
   * - 2024-05-30
     - tutorial
     - How to do synthetic source injection (Jeff Carlin)
   * - 2024-06-06
     - drop-in
     - Q&A with Rubin staff, co-working time
   * - 2024-06-13
     - tutorial
     - Custom source detection pipeline (Aaron Meisner)
   * - 2024-06-20
     - none
     - :doc:`rubin-data-academy-2024`
   * - 2024-06-27
     - tutorial
     - Near-Earth objects in DP0.3 (Sarah Greenstreet)
