.. Review the README on instructions to contribute.
.. Review the style guide to keep a consistent approach to the documentation.
.. Static objects, such as figures, should be stored in the _static directory. Review the _static/README on instructions to contribute.
.. Do not remove the comments that describe each section. They are included to provide guidance to contributors.
.. Do not remove other content provided in the templates, such as a section. Instead, comment out the content and include comments to explain the situation. For example:
	- If a section within the template is not needed, comment out the section title and label reference. Do not delete the expected section title, reference or related comments provided from the template.
    - If a file cannot include a title (surrounded by ampersands (#)), comment out the title from the template and include a comment explaining why this is implemented (in addition to applying the ``title`` directive).

.. This is the label that can be used for cross referencing this file.
.. Recommended title label format is "Directory Name"-"Title Name" -- Spaces should be replaced by hyphens.
.. _DP0-Delegate-Resources-Virtual-Events-Schedule:
.. Each section should include a label for cross referencing to a given area.
.. Recommended format for all labels is "Title Name"-"Section Name" -- Spaces should be replaced by hyphens.
.. To reference a label that isn't associated with an reST object such as a title or figure, you must include the link and explicit title using the syntax :ref:`link text <label-name>`.
.. A warning will alert you of identical labels during the linkcheck process.

.. This file does not contain a title because it is a table for another location (dp0-delegate-resources/index.rst).
.. title:: DP0 Delegate Assemblies Schedule
.. ################################
.. DP0 Delegate Assemblies Schedule
.. ################################

.. This section should provide a brief, top-level description of the page.

.. Use *italics* for tentative topics.

.. Use double-underscore for external links to prevent duplicate explicit target names.

.. list-table:: Rubin Science Assemblies schedule
   :header-rows: 1
   :widths: 1 1 3

   * - Date
     - Type
     - Topic
   * - 2024-10-03
     - tutorial
     - Douglas Tucker: A (Re-)Introduction to DP0
   * - 2024-10-10
     - drop-in
     - team members available for support
   * - 2024-10-17
     - presentation
     - Participating in Rubin First Look
   * - 2024-10-24
     - drop-in
     - team members available for support
   * - 2024-10-31
     - tutorial
     - Aaron Meisner: Butler from the Command Line
   * - 2024-11-07
     - drop-in
     - team members available for support
   * - 2024-11-14
     - tutorial
     - topic
   * - 2024-11-21
     - drop-in
     - team members available for support
   * - 2024-11-28
     - CANCELLED
     - (American Thanksgiving)
   * - 2024-12-05
     - drop-in
     - team members available for support
   * - 2024-12-12
     - presentation
     - Data Preview 0 Review: Thank You Delegates!
   * - 2024-12-19
     - CANCELLED
     - (winter break)
   * - 2024-12-26
     - CANCELLED
     - (winter break)
   * - 2025-01-02
     - CANCELLED
     - (winter break)
   * - 2025-01-09
     - tutorial
     - Yumi Choi: how to join user-uploaded tables in RSP
   * - 2025-01-16
     - drop-in
     - team members available for support
   * - 2025-01-23
     - tutorial
     - topic
   * - 2025-01-30
     - tutorial
     - Looking forward to Data Preview 1
   * - 2025-02-13
     - drop-in
     - team members available for support
